#!/bin/bash

#SBATCH --job-name=sander_scaling
#SBATCH --output=sander-test_%j.out
#SBATCH --error=sander-test_%j.err
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=40
#SBATCH --cpus-per-task=1
#SBATCH --mem=6G
#SBATCH --time=1000:00:00
#SBATCH --partition=cpu
#SBATCH --nodelist=cpu-2-4

# Load mpi environment
export PATH=/home8/larry/apps/openmpi/3.1.6/bin/:$PATH
export LD_LIBRARY_PATH=/home8/larry/apps/openmpi/3.1.6/lib/:$LD_LIBRARY_PATH

# Environment variables setup
if [ -z "$TESTsander" ]; then
    TESTsander="/home8/larry/amber24/bin/sander.MPI"
fi


for i in 1 3 5 7; do
# Prepare input file
cat > mdin${i} <<EOF
 single point calc.
 &cntrl
   imin=0, nstlim=10000,
   irest=1, ntx=5, 
   ntt=1, temp0=300,
   ntb=1, ntp=0,
   ntc=2, ntf=2, tol=0.000001,
   cut=9.,
   ntpr=100000, ntwr=100000, ntwx=100000,
   dt=0.001,
   ipgm=0,
 /
 &ewald
  skinnb=2.,ew_coeff=0.4,order=5,vdwmeth=0
 /
 &pol_gauss
   pol_gauss_verbose=0,ee_dsum_cut=9.0,
   dipole_scf_tol=0.01,dipole_scf_init=3,dipole_scf_init_order=2,dipole_scf_init_step=4,
   scf_solv_opt=3,scf_sor_niter=100,scf_sor_coefficient=0.65,
   scf_cg_niter=100,scf_local_niter=3,scf_local_cut=4.0
 /
EOF

# Execute the program
$TESTsander -O -i mdin${i} -p sys${i}-pgm_updated.prmtop -c sys${i}-pgm-nvteq.rst -o sys${i}_1-tip.out
done
