#!/bin/bash

#SBATCH --job-name=ncpu_test
#SBATCH --output=sander-test_%j.out
#SBATCH --error=sander-test_%j.err
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --time=1000:00:00
#SBATCH --partition=gpu


# Load mpi environment
export PATH=/home/larry/apps/openmpi/3.1.6/bin/:$PATH
export LD_LIBRARY_PATH=/home/larry/apps/openmpi/3.1.6/lib/:$LD_LIBRARY_PATH

# Environment variables setup
if [ -z "$TESTsander" ]; then
    TESTsander="/home/larry/amber24/bin/sander"
fi

i=7
# Prepare input file
cat > mdin <<EOF
 single point calc.
 &cntrl
   imin=0, nstlim=100000,
   irest=0, ntx=1, 
   ntt=0, temp0=300,
   ntb=1, ntp=0,
   ntc=2, ntf=2, tol=0.000001,
   cut=9.,
   ntpr=100000, ntwr=100000, ntwx=100000,
   dt=0.001,
   ipgm=0,
 /
 &ewald
  skinnb=2.,ew_coeff=0.4,nfft1=50,nfft2=50,nfft3=50,order=8,vdwmeth=0
 /
 &pol_gauss
   pol_gauss_verbose=0,ee_dsum_cut=9.0,
   dipole_scf_tol=0.01,dipole_scf_init=3,dipole_scf_init_order=2,dipole_scf_init_step=4,
   scf_solv_opt=3,scf_sor_niter=100,scf_sor_coefficient=0.65,
   scf_cg_niter=50,scf_local_niter=3,scf_local_cut=4.0
 /
EOF

# Execute the program
$DO_PARALLEL $TESTsander -O -i mdin -p sys${i}-tip3p.prmtop -c sys${i}.crd -o sys${i}_1-tip3p.out

